---
- name: Install and configure TruffleHog
  hosts: all
  become: true
  tasks:
    - name: Install TruffleHog via apt
      apt:
        name: trufflehog
        state: present
        update_cache: true

    - name: Check TruffleHog version
      command: trufflehog --version
      register: trufflehog_version
      changed_when: false

    - name: Display TruffleHog version
      debug:
        var: trufflehog_version.stdout
