---
- name: Install and configure Subfinder via apt
  hosts: all
  become: true
  tasks:
    - name: Install Subfinder via apt
      apt:
        name: subfinder
        state: present
        update_cache: true

    - name: Check installed version of Subfinder
      command: subfinder -v
      register: subfinder_version
      changed_when: false

    - name: Display Subfinder version
      debug:
        var: subfinder_version.stdout
